### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by nkprince007** [adtac/commento#126]
The current implementation of comments lacks full markdown support and I'm not sure it's a point of discussion for the near future. 

But it'd be nice to at least have some free licensed open-source emojis like [emojione](https://github.com/emojione/emojione) or [emojify](https://github.com/emojione/emojify.js).

**Comment by adtac** [comment]
By emoji do you mean `:word:` to symbols or the unicode characters themselves?

Unicode is already supported FWIW.

**Comment by nkprince007** [comment]
Yeah, I meant `:word:` symbols.

**Comment by adtac** [comment]
I just want to quickly add that I don't want smileys turning into emojis. Gitter's stupid emojis for smileys make me physically wince in pain.

`:tada:` turning into :tada: is fine, but `:)` turning into 😄 is not.

**Comment by nkprince007** [comment]
Yeah. That’s especially annoying and unintended.

**Comment by Trollwut** [comment]
You might look into Mastodon's implementation of emojis. Smileys keep being smileys, but for every emoji there is a `:description_of_emoji:` way around. They also have that emoji-button, where a selection window pops up to insert the unicode character.

**Comment by adtac** [comment]
@nkprince007 @Trollwut @Avamander @davidak @dertuxmalwieder @NightMachinary (some of you are mentioned because you've shown interest in this issue with :+1:): This issue is still definitely possible.

We have, however, moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, this comment has been exported to https://gitlab.com/commento/commento-ce/issues/30 (with a link back to this issue for history).
