### ISSUE TITLE
Add a way to self-host Commento without using Docker?

### ISSUE THREAD

**Issue by aravindhsampath** [adtac/commento#146]
Commento looks neat for use in personal website. 

Any chance you could provide instructions to build Commento on a Unix/Linux Server with out using Docker?

I understand I can look into the DockerFile, but I'm not proficient with Docker/npm to do it right.

It would be amazing to have a workflow like that of [HomeBrew](https://brew.sh) where you download a script that downloads the latest version of Commento, configures it based on user entered parameters and spits out a binary that can run on the server.

**Comment by adtac** [comment]
You have two options if you don't want to use Docker:

 - use the amd64 linux release binaries: https://github.com/adtac/commento/releases - but since you mentioned Homebrew I think this might not be the option for you.

 - build from source: this will work for pretty much every arch/OS.

I should mention this in the docs. When I wrote the README, I didn't really make proper point releases, so docker was the best option. But now that there are releases (latest version: 0.2.1), you can simply run the binary.

**Comment by adtac** [comment]
I'll make a commit fixing that later tonight.
