### ISSUE TITLE
TypeError: t is null error

### ISSUE THREAD

**Issue by somenxavier** [adtac/commento#148]
Details in firefox inspector:
```
TypeError: t is null
[Més informació]
commento.min.js:1:1894
x
http://localhost:8081/assets/commento.min.js:1:1894
B.init/<
http://localhost:8081/assets/commento.min.js:1:6182
f/r.onload
http://localhost:8081/assets/commento.min.js:1:1236
```

**Comment by adtac** [comment]
Unfortunately, this is not a very useful error report - since `commento.min.js` is minified, it'll be difficult for me to infer anything from this. Instead of:

```html
<script src="http://127.0.0.1/assets/commento.min.js"></script>
```

... can you use:

```html
<script src="http://127.0.0.1/assets/commento.js"></script>
```

and provide me with the error report from firefox inspector?

Thanks!

**Comment by somenxavier** [comment]
Here you have it:
```
TypeError: el is null
[Més informació]
commento.js:182:9
addEvent
http://localhost:8081/assets/commento.js:182:9
Commento.init/<
http://localhost:8081/assets/commento.js:603:13
loadJS/script.onload
http://localhost:8081/assets/commento.js:120:17
```

**Comment by schollz** [comment]
I'm getting something similar:

```
TypeError: el is null
[Learn More]
commento.js:182:9
addEvent
http://localhost:1313/js/commento.js:182:9
Commento.init/<
http://localhost:1313/js/commento.js:603:13
loadJS/script.onload
http://localhost:1313/js/commento.js:120:17
```

**Comment by adtac** [comment]
Thanks a lot for reporting this, @somenxavier and @schollz 

Looking into it.

**Comment by adtac** [comment]
@schollz @somenxavier I'm afraid this issue is now really outdated, so I'm closing this issue. There's a completely new version (basically a rewrite), and if you're still facing this issue, please file a different issue. The old version (for which you reported the error) has been deprecated.

BTW, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). If you need to file a new issue, please create one over there.
