### ISSUE TITLE
Private comments

### ISSUE THREAD

**Issue by jayvdb** [adtac/commento#156]
I have a use case for adding the ability for a small group of predefined users to discuss webpages 'privately', but the conversation needs to be captured/archived.

https://gitlab.com/ciptamedia/ciptamedia-dev.gitlab.io/issues/59

**Comment by adtac** [comment]
Is the webpage itself private or do you want a private discussion on a public webpage? If latter, is a different URL for the discussion page okay?

**Comment by adtac** [comment]
Basically, my idea is this: since the URL associated with each comment can be modified (not right now, but can be done with a couple of tiny changes), you pass the public page's URL when loading Commento. The page itself can be private (behind basic auth, for example).

**Comment by jayvdb** [comment]
The page is currently public, and the source code is public, but it is hosted on Netlify unpaid plan so [http auth](https://www.netlify.com/docs/headers-and-basic-auth/) is not available.

The way to obtain the private comments out of Commento needs to be protected.

It sounds like the server with private comments needs to be isolated from any public comments, otherwise fiddling with the URL could result in private comments being exposed.

So I guess I would need host an isolated instance of Commento somewhere with HTTP basic auth enabled, and make the page also private (doable).

**Comment by adtac** [comment]
Ah, I see. The API needs to be behind authentication as well since otherwise it'll just be security by obscurity (others can't access comments *only* because they don't know the second API domain). I'll think about the best way this can be implemented in the backend.

**Comment by adtac** [comment]
@jayvdb Thanks a lot for this issue! This is more possible now than before, I think, because of the moderation dashboard, etc. Maybe we could have a list of email addresses that are allowed to list/get comments, and require authentication.

Anyway, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, this comment has been exported to https://gitlab.com/commento/commento-ce/issues/38 (with a link back to this issue for history).
