### ISSUE TITLE
Homepage field

### ISSUE THREAD

**Issue by davidak** [adtac/commento#158]
It would be nice if commentators could add the URL of their Homepage, so their name is a link to it.

This way you can find out more about the people commenting.

**Comment by adtac** [comment]
Excellent idea :+1:

This will work even better when authentication is implemented. People can use something like Google OAuth which will automatically give us a link to their Google profile, for example.

**Comment by adtac** [comment]
However, we really need to make sure this isn't used for spam.

**Comment by dertuxmalwieder** [comment]
In most cases, that feature does not add a value to a discussion, honestly.

**Comment by davidak** [comment]
@dertuxmalwieder not directly, but it helps to build a community with other bloggers and readers.

I actually found reallife friends from comments on my wordpress blog.

**Comment by SnorlaxYum** [comment]
@adtac You could add a function allowing users to disable the URL field. Thus whether to have a URL field is up to the user.  
I like this idea, too.  
If u add this feature, much more people will like to jump to commento.  
It's a must for many people like me.

**Comment by adtac** [comment]
@davidak @dertuxmalwieder @SnorlaxYum This feature has now been implemented! In the latest version of Commento (basically a rewrite), you now have the option to enter your website when you want to create an account to comment.

BTW, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). So I'm closing this issue for two reasons: this has been implemented, and all issues are now being moved to GitLab. Cheers!

**Comment by adtac** [comment]
Here's what it looks like:

![screenshot from 2018-06-11 18-37-36](https://user-images.githubusercontent.com/7521600/41233251-8b0c1352-6da6-11e8-896e-adff9aee6026.png)

**Comment by dertuxmalwieder** [comment]
The move to Gitlab is irritating. Is it because Github belongs to a major company now while Gitlab... is a different company?

**Comment by adtac** [comment]
No, I'm not moving to Github because of the microsoft acquisition. I had been planning this for months. The MS acquisition news broke, like, 2 weeks ago.

Four reasons:

 - Gitlab has so many extra features that it's not even funny how far behind Github is. Basic quality of life improvements like FF merges, merge on pipeline success, namespaced repos, etc. are missing from Github.
 - Github really sucks when it comes to fine-grained developer permissions, especially for user repos.
 - Gitlab has superior CI. I have set up personal runners in a VPS (because Gitlab's default runners, while perfectly fine, have a startup latency) and I face literally zero delay in running tests, builds and static analysis.
 - Gitlab CE is open source. I know that their whole product isn't free software, but something is better than nothing.
 - And finally, a fifth reason, although it played practically zero role in my decision: the `@commento` username wasn't available on Github, while it was on Gitlab.

MS buying Github only strengthened my already strong resolve to move.

**Comment by adtac** [comment]
Oh, and I may also want the option to export all org-related data for custom hosting that doesn't depend gitlab.com in the future. AFAIK, github doesn't any such option right now (and I don't expect them to add this any time soon to support their on-prem hosting product because they're heavilty betting on a service model).

**Comment by dertuxmalwieder** [comment]
I see. Thank you!
