### ISSUE TITLE
Missing packages during build... cannot find package "github.com/joho/godotenv"

### ISSUE THREAD

**Issue by DoctorBud** [adtac/commento#161]
I'm building via `go build`, and I got the following errors:
```bash
config.go:4:2: cannot find package "github.com/joho/godotenv" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/github.com/joho/godotenv (from $GOROOT)
	/Users/myuser/go/src/github.com/joho/godotenv (from $GOPATH)
main.go:8:2: cannot find package "github.com/mattn/go-sqlite3" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/github.com/mattn/go-sqlite3 (from $GOROOT)
	/Users/myuser/go/src/github.com/mattn/go-sqlite3 (from $GOPATH)
main.go:9:2: cannot find package "github.com/op/go-logging" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/github.com/op/go-logging (from $GOROOT)
	/Users/myuser/go/src/github.com/op/go-logging (from $GOPATH)
```

I fixed the problem by installing the dependencies with:

```bash
go get github.com/joho/godotenv github.com/mattn/go-sqlite3 github.com/op/go-logging
```

and now the build succeeds. So I have a workaround.

I'm not a Go programmer, so I'm not sure of the correct fix. Presumably some config file needs to be changed to make these dependencies explicit. I'm creating this issue mostly for anyone else who runs into this.

**Comment by adtac** [comment]
Hmm, I wonder how the CI didn't pick this up. I'll take a look at this, thanks for reporting!

**Comment by arpang** [comment]
I ran into the same issue!

**Comment by adtac** [comment]
@DoctorBud @arpang Thanks a lot for this issue! I think this issue is now really outdated; we have new version of Commento (basically a rewrite), and I don't think this issue is present there. The older version has been deprecated.

BTW, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). So I'm closing this issue for two reasons: I think this has been fixed, and all issues are now being moved to GitLab. Cheers!
