### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by prologic** [adtac/commento#163]
Can you provide a demo?

**Comment by adtac** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by adtac** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/adtac/commento/issues/41 (Demo comment deletion), https://github.com/adtac/commento/issues/47 (Reduce demo env logging verbosity), and https://github.com/adtac/commento/issues/80 (the live demo does not work).

**Comment by adtac** [comment]
@prologic you can find the demo here: https://commento.adtac.pw/
