### ISSUE TITLE
Import Isso's database file into Commento

### ISSUE THREAD

**Issue by SnorlaxYum** [adtac/commento#166]
Is the database file of isso usable in commento?  
If not, then how to convert it to the one used by commento?

**Comment by adtac** [comment]
Isso's db file isn't compatible with Commento out of the box, but a script to convert it might be possible.

Renaming this issue.

**Comment by SnorlaxYum** [comment]
@adtac If u r planning to do this, consider do the issue #158 as well. 'Cause isso contains homepage field.

**Comment by adtac** [comment]
@SnorlaxYum thanks a lot for this issue! This issue is still very much valid.

We have, however, moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, this comment has been exported to https://gitlab.com/commento/commento-ce/issues/39 (with a link back to this issue for history).
