### ISSUE TITLE
Headless, APIs?

### ISSUE THREAD

**Issue by decimoseptimo** [adtac/commento#174]
https://www.gatsbyjs.org/blog/2018-04-10-how-to-handle-comments-in-gatsby-blogs/#client-side

Have you think about REST/GraphQL APIs? Is it in the project scope?

**Comment by adtac** [comment]
REST: I originally wanted the API to be REST-compatible, but went and implemented a custom solution.

GraphQL: I haven't used this before, but it looks very interesting!

To both: yes, this is definitely in the project scope, but maybe not a priority at the moment. The API itself is changing rapidly (we're still in 0.x), so I think it makes sense to add these after we achieve API stability.

**Comment by adtac** [comment]
@decimoseptimo I'm closing this issue because we've achieved a stable API design in the new version (basically a rewrite) and I don't think we'll be making drastic changes. The old version (see branch `v0`) is still unchanged.

BTW, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). So I'm closing this issue. Cheers! Feel free to create a new issue in teh gitlab repo.
