### ISSUE TITLE
No commento.min.js in the 0.3.1 release

### ISSUE THREAD

**Issue by chenxsan** [adtac/commento#177]
I'm running commento [0.3.1](https://github.com/adtac/commento/releases/tag/v0.3.1) on my server, and found that there's no `commento.min.js`, only `commento.js`. Also `commento.js` is trying to load `commento.min.css` that doesn't exist.

Thought it needs minified first before release?

**Comment by adtac** [comment]
@chenxsan @rseen Thanks a lot for this issue! This is a valid issue, but I think there won't be a fix for this because the old version has been deprecated in favour of the new version (basically a rewrite).

BTW, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). So I'm closing this issue. If you see a mistake in future releases in the new version, feel free to create an issue in the Gitlab repo. Cheers!
