### ISSUE TITLE
Show the use an error on a permissions problem

### ISSUE THREAD

**Issue by jamesbvaughan** [adtac/commento#183]
I ran into an issue recently where my commento process did not have write permissions on my database file. When a user tries to post a comment in this situation, they just see a never-ending spinner.

I think it would be more helpful to have a timeout, after which the user is shown an error message indicating that there was a problem posting their comment on the server-side.

**Comment by adtac** [comment]
@jamesbvaughan I'm afraid this issue is specific to the old, deprecated version, too. That version has been retired, and will not receive any patches apart from some critical security patches. The new version (basically a rewrite), as you know, is way more complete and featureful.

Anyway, I'm closing this issue because we're [moving all developmen to Gitlab](https://gitlab.com/commento/commento-ce). Cheers!
