### ISSUE TITLE
Feedback saying that the comment got posted?

### ISSUE THREAD

**Issue by kaushalmodi** [adtac/commento#19]
I just tried out the demo site over phone. The good news is that it works. But it took me a moment to realize that the comments were actually getting posted.

- There was no feedback saying that the commented got posted. I was expecting a green background hover text saying that that happened and then disappeared. But it felt like nothing happened.. and I tapped the button few times. Turns out I ended up with the same comment multiple times.
- Also the comments end up at the bottom of the thread. May be that depends on preference, but I somehow expected my comment to show up at the top of the thread.

**Comment by adtac** [comment]
>feedback saying the commented got posted

There are [toast notificaations](https://picturepan2.github.io/spectre/components.html#toasts) in Spectre (the CSS library I'm using (because I'm a JS/CSS noob)). Maybe we could use that.

>the comments end up at the bottom of the thread.

Yeah, some users wanted chronological sorting. Maybe a compromise would be temporarily show your comment at the top and then show it at the bottom when you refresh. But I feel that's needlessly complicating stuff.

Anyway, I'm planning on implementing voting. So when that happens, that'll be the default.

**Comment by DarkThrone** [comment]
We could implement a gif or an svg image to for visual feedback on the button. That should be farily easy, and we could implement that entirely on the front-end.

<img width="344" alt="screen shot 2017-04-30 at 11 36 17" src="https://cloud.githubusercontent.com/assets/565726/25560516/5ab18870-2d99-11e7-8e6d-11a0328008c5.png">

**Comment by adtac** [comment]
That sounds neat. At completion, it could become a tick and last for a couple of seconds (or until the user focuses on the textarea again).

**Comment by adtac** [comment]
We can add a `disabled` attribute too. That'll prevent double-clicking and double-posting.

**Comment by rodorgas** [comment]
What if we place the comment on top? Even if it's on chronological order, we should put the new comment on top just for feedback. If the user refreshes the page, his comment will go to correct position. I've just checked and this is the disqus behaviour.

Animations and other visuals clues won't solve this issue IMO, because the user simply is not seeing his comment.

**Comment by adtac** [comment]
@rodorgas how about moving to the comment with a `#comment-id` hash in the URL?

**Comment by adtac** [comment]
I've added the spinner thing: on pressing "Post", the button is disabled and made into a spinner. At the end of all HTTP requests, it's un-disabled and the spinner is removed.

The "your comment should be at the top on posting" part is a little different, so I'll open a different issue for that.

**Comment by rodorgas** [comment]
Scrolling to the comment seems a great solution. The comment could be briefly highlighted, also.
