### ISSUE TITLE
Add "sticky" comments

### ISSUE THREAD

**Issue by rrggrr** [adtac/commento#24]
Add comments that always appears at the top.

**Comment by klebervirgilio** [comment]
Hey! I would like to help. :)

How would like to do that? 

As I see we could set an order attribute on comment... this way we can pin more than one comment.

What do you think?

**Comment by adtac** [comment]
This would require some kind of admin dashboard, which we don't have at the moment. Currently all users are equal (because we literally have zero ways to differentiate - no IP logs, no cookies, nothing).

**Comment by klebervirgilio** [comment]
Good point. We could implement some kind of `vote|thumbs up|endorsement|like` where the most voted comment, and only the most voted gets sticked (something like stackoverflow). This way votes|likes|endorsements would only be a integer field being incremented anonymously. 

How does that sounds?

**Comment by adtac** [comment]
@klebervirgilio yeah, voting is a upcoming feature. But we can't have an anonymous integer field: the same person will then be able to vote twice. Some form of tracking is inevitable if we want stuff like voting, deleting, editing comments, stickying.

One idea someone suggested was to (one-way) hash the IP address of the user and use that as identity. That way, we don't really track the user's IP address, but we also allow them unique control over their content.

Maybe a concatenation of IP address + unique cookie will work better. This way, two people behind the same IP will not be able mistakenly edit the other's comment (this is pretty common in places like universities).

**Comment by klebervirgilio** [comment]
Sounds like the way to go! :) thanks!

Wondering which would be the better way to stick a comment. 

I'm tempted to stick the most "voted|liked" comment. 

PS: Which terminology should we use? `votes`? `likes`? `endorsements`?

**Comment by adtac** [comment]
@klebervirgilio I think we should allow the moderator to sticky the comment instead of doing it based on voting (because when we implement voting, sorting by votes will automatically push the most upvoted comment to the top).

This is kinda dependent on https://github.com/adtac/commento/issues/25 - a proper moderator feature should be in place before this is possible IMO.

You are welcome to try your hand at both of course ;) But ideally, we'd have the moderation feature first before this :)

**Comment by adtac** [comment]
And once we actually implement a moderation feature, it becomes way easier to do this.

But moderation will need a lot of design and discussion, so let's see how that goes.

**Comment by thesimpledesigners** [comment]
`IP address + unique cookie will work better`
what about spamming doesn't that clutter the server with so many hashed ip's specially when using a bot or using a tor network

**Comment by Superman132** [comment]
Instead of IP + unique cookie, I think email + up will be better because there won't be a need to store and track cookies on user

**Comment by adtac** [comment]
@rrggrr @klebervirgilio @thesimpledesigners @Superman132 Thanks a lot for the issue! This is definitely possible now in the new version since we have an admin panel, a moderator dashboard, etc.

We have, however, moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, this comment has been exported to https://gitlab.com/commento/commento-ce/issues/24 (with a link back to this issue for history).
