### ISSUE TITLE
Introduce a front-end build pipeline

### ISSUE THREAD

**Issue by DarkThrone** [adtac/commento#43]
I believe Commento should have a build pipeline for it to allow concurrent working streams without generating merge conflicts.

In the current situation if two people were to work on a JavaScript or CSS issue, or even the same person working on two separate issues, then PR order turns into a bottle neck.

My solution to this problem is to introduce a low footprint build pipeline for the front-end. This pipeline would be in charge of cleaning previous processed resources, linting the resource to maintain style and code correctness, minify and compress the source files, and rename the resource for a production ready environment.

This would also introduce some dependencies like NPM and gulp (I prefer Gulp over Grunt, but that's another discussion entirely different). 

The approach would be to create a new `package.json` file with the dependencies, a `Gulpfile.js` to declare the build steps, and a `Dockerfile.build` file to run all this in a docker container to avoid tainting the host environment.

I'm already working on a solution like this. I should have a PR ready in a couple of days.

Please, share your thoughts.

**Comment by adtac** [comment]
I agree, the current way is too much of an hassle during merges. I had to cherry-pick 8 or so PRs and discard all changes to the minified files at each stage (because of merge conflicts) and apply my own minification (I use the [`minify` package](https://github.com/tdewolff/minify)).

I just have a question: say I create a commit changing a couple of things in the unminified JS. I shouldn't touch the minified JS, right? The pipeline would generate the minified file and then commit it? So that'd be one extra commit per PR?

And I have no problem with the dependencies: they are entirely for the front-end, so I don't imagine that'd be an issue. TBH I don't have any experience with frontend development, so I'm just going to trust you on this :)

**Comment by adtac** [comment]
@DarkThrone I think we have this now.

BTW, we've moved all development [to GitLab](https://gitlab.com/commento/commento-ce). So I'm closing this issue as all issues are now being moved to GitLab. Cheers!
