### ISSUE TITLE
GET request for retrieving comments does not work

### ISSUE THREAD

**Issue by smbkr** [adtac/commento#76]
GET request to retrieve comments does not work, as in http.go:80, we are retrieving the url from r.PostFormValue.

Perhaps the url we want to retrieve comments for should be sent as a header, so that a GET or POST request can be used in the same way? Or use some conditional logic to either retrieve the value from PostFormValue or some other method (query param seems preferable) for a GET request.

If anyone has a preference either way or some insight as to what may work best, let me know. I will attempt to look at this tomorrow/Friday, if I am able.

**Comment by modInfo** [comment]
`{success: false, message: ""}
message:""
success:false`

i cant write any comments

**Comment by GaiusMartius** [comment]
That's in issue I tried to work out myself. Getting comments should be a GET operation but we use POST so that data (the url which acts as an ID for the page) can be sent to grab the relevant comments.

I tried to add a 'get' function to the commento.js. The idea was to submit the url as a cookie and then perform GET to retrieve the comments. I can't running into issues related to CORS.
Maybe you will have better luck.

**Comment by adtac** [comment]
Assigned you, @smbkr

**Comment by adtac** [comment]
@smbkr @GaiusMartius I'm afraid this issue is no longer valid in the new version (basically a rewrite).

We have also moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, I'm closing this issue as I want to make the GitLab repo the central point of development (plus this bug isn't present in the new version). This Github repo will still exist, it's just a mirror now.
