### ISSUE TITLE
Additional route /count

### ISSUE THREAD

**Issue by kWeb24** [adtac/commento#78]
Returns number of comments using post URL as parameter. 

Useful for main page post list and allow to create new comment notify without getting all the comments from db.

**Comment by adtac** [comment]
Assigning you, @smbkr (maybe mentioning you will enlist you in the assignee list :P)

**Comment by adtac** [comment]
@kWeb24 Thanks a lot for the issue! This issue is still valid in the new version (basically a rewrite).

We have, however, moved all development [to GitLab](https://gitlab.com/commento/commento-ce). Therefore, this comment has been exported to https://gitlab.com/commento/commento-ce/issues/27 (with a link back to this issue for history). Cheers!
